"""add chunks search_vector fts column

Revision ID: 1411acc677a2
Revises: 6b4973f2d011
Create Date: 2026-08-18 07:27:22.923210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1411acc677a2'
down_revision: Union[str, None] = '6b4973f2d011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False))
    # ### end Alembic commands ###

    # Hand-added: autogenerate detects the column but not the index it needs —
    # a GIN index is the standard, recommended index type for tsvector full-
    # text search (btree, SQLAlchemy's mapped_column(index=True) default,
    # doesn't support the @@ match operator at all).
    op.create_index(
        "ix_chunks_search_vector",
        "chunks",
        ["search_vector"],
        postgresql_using="gin",
    )


def downgrade() -> None:
    op.drop_index("ix_chunks_search_vector", table_name="chunks")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'search_vector')
    # ### end Alembic commands ###
